### ISSUE TITLE
arch install error

### ISSUE THREAD

**Issue by se7en-x230** [darkhz/bluetuith#1]
go installs but bluetuith command not found and installing from the release 

`error: missing package metadata in Downloads/bluetuith_0.0.1_Linux_x86_64.tar.gz
error: 'Downloads/bluetuith_0.0.1_Linux_x86_64.tar.gz': invalid or corrupted package
`

**Comment by darkhz** [comment]
What program are you using to extract the binary from the tar ball? 

I was able to extract the binary using tar:
`tar -xvzf bluetuith_0.0.1_Linux_x86_64.tar.gz`

and by using the Archive Manager application.

As for installing via `go`, ensure that your $HOME/go/bin is in your $PATH.

**Comment by se7en-x230** [comment]
I used pacman.

pacman -U bluetuith_0.0.1_Linux_x86_64 
That gives me the missing metadata error.

**Comment by darkhz** [comment]
You can't use pacman to extract and install from the archive file, it is merely a tarball. Use tar or any archive program to extract and use it.

Alternatively, since the package is now in the AUR, you can use the following command to install it:
`pacman -S bluetuith-bin`

**Comment by se7en-x230** [comment]
Nice one. Thanks
