### ISSUE TITLE
Cant see any device names

### ISSUE THREAD

**Issue by yeetus-maximus** [darkhz/bluetuith#11]
![Uploading 2023-01-18-170832_1920x1080_scrot.png…]()

**Comment by darkhz** [comment]
Provide a detailed description of your issue and re-upload your screenshot.

**Comment by darkhz** [comment]
This issue will be closed, due to inactivity. You can reopen it with the criteria mentioned above.

**Comment by yeetus-maximus** [comment]
its quite hard to describe almost nothing.

![2023-01-18-170832_1920x1080_scrot](https://user-images.githubusercontent.com/76941455/213930580-64adf736-0ed1-4bc0-b2cd-69cdd5339698.png)

**Comment by darkhz** [comment]
Is bluetoothctl able to list devices? Is bluez working and enabled? Have you tried to scan for devices and see if any devices pop up on the screen?
