### ISSUE TITLE
how can auto scan

### ISSUE THREAD

**Issue by newyorkthink** [darkhz/bluetuith#16]
when i enter bluetuith

![image](https://github.com/darkhz/bluetuith/assets/87791643/6db4a3b9-699a-4377-a717-b38b1498f746)
is just not scan

and i always enter s ,i scan

![image](https://github.com/darkhz/bluetuith/assets/87791643/f555fa28-4494-436c-8780-d2f90971d5d4)

so how can bluetuith start and auto scan driver

**Comment by darkhz** [comment]
Currently there is no way to auto-scan on launch, but I can implement this

**Comment by frankier** [comment]
I agree it's would be a nice default behavior, possibly with some option to disable

**Comment by darkhz** [comment]
This feature has now been implemented with the `adapter-states` command-line option.

To scan automatically on initialization, it can be done via the command-line: 
```
bluetuith --adapter=<adapter> --adapter-states="powered:on, scan:on"`
```

Or by setting the configuration parameter:
```
adapter-states: "powered:on, scan:on"
```
