### ISSUE TITLE
new version cannot close

### ISSUE THREAD

**Issue by newyorkthink** [darkhz/bluetuith#17]
when i close bluetuith, use q, or ctrl c is not work 
so i just use kill command.

and i kill bluetuith.
it show look this
![image](https://github.com/darkhz/bluetuith/assets/87791643/62b6bafa-0578-411d-9c90-6ff606e0ba98)

cannot run anything

**Comment by darkhz** [comment]
The new keybinding is now Shift+q, I forgot to update the docs, I'll do it
soon. See #8.

**Comment by darkhz** [comment]
The new keybinding is Shift+q, I forgot to update the docs, I'll do it soon. See #8.

**Comment by sabrehagen** [comment]
@darkhz can this change be added to `invidtui` too please

**Comment by darkhz** [comment]
@sabrehagen sure

**Comment by sabrehagen** [comment]
@darkhz seeing as no other function is bound to `q`, why not make `q` quit? `q` is common throughout many tui utilities as the method of exit, I have never encountered `Shift+q` before.

**Comment by darkhz** [comment]
It's very easy to accidentally press 'q', so I think Ctrl+C may be a more suitable choice.

**Comment by sabrehagen** [comment]
I would disagree, for a competent user 'q' is not usually an issue. Writers of `less`, `more`, etc. i.e. unix core tools must not have felt it was an issue.

**Comment by darkhz** [comment]
That's true, let me look into this
