### ISSUE TITLE
Menu close delay

### ISSUE THREAD

**Issue by sabrehagen** [darkhz/bluetuith#18]
After opening the menu with `Ctrl+m`, I close the menu with `Esc`. After pressing `Esc` there is a one second delay before the menu closes. What is the cause of this delay? Can it be removed?

**Comment by darkhz** [comment]
I can't reproduce this issue on my end, when I press Ctrl+m and Esc the menu closes immediately. Can you record a gif/video of the issue?

**Comment by sabrehagen** [comment]
This video shows the delay I observe. Somewhere between 0.5-1.0 sec. Do you observe the same?

https://github.com/darkhz/bluetuith/assets/1094600/05a0ed23-e13f-4637-a2cf-9fb289ca2a27

**Comment by darkhz** [comment]
Interesting, I will look into it.

**Comment by darkhz** [comment]
Hmm, this may be a very trivial question, but can you perhaps try it in a different terminal emulator? I cannot reproduce it on my end, the menu dialog closes immediately for me

**Comment by sabrehagen** [comment]
Yes, testing in xterm has no delay. Delay is experienced in alacritty.
