### ISSUE TITLE
See keybindings in the application

### ISSUE THREAD

**Issue by tvararu** [darkhz/bluetuith#2]
Hello! This is great. Much easier to use than `bluetoothctl`, and thanks for making it.

It would be helpful if the application included an easy way to see all the keybindings; same table as the one in the README.

Here's a screenshot of how `pulsemixer` does it, triggered by pressing the `?` key, side by side with `bluetuith`:

![image](https://user-images.githubusercontent.com/1650875/179685877-f978c179-2040-4500-9b1c-bd4e5401d8a3.png)

**Comment by darkhz** [comment]
The keybindings can be viewed by opening the menu (press Ctrl+m). A dedicated help page/dialog, however, will  be more convenient. Thank you for the suggestion, I will implement this feature.

**Comment by darkhz** [comment]
The keybindings can be viewed by opening the menu (press Ctrl+m). A dedicated help page/dialog, however, will be more convenient. Thank you for the suggestion, I will implement this feature.

**Comment by tvararu** [comment]
Thanks a lot for this! I'll try it out ASAP :D
