### ISSUE TITLE
 how can store connected info in .config/bluetuith

### ISSUE THREAD

**Issue by newyorkthink** [darkhz/bluetuith#22]
when i recover system, i always reconnected my bluetooth,

**Comment by darkhz** [comment]
Can you elaborate? The issue description looks like it's incomplete.

**Comment by newyorkthink** [comment]
> Can you elaborate? The issue description looks like it's incomplete.

i mean is, when i reinstall my os, the bluetooth info is empty, so ,how can store my bluetooth info in new os

**Comment by darkhz** [comment]
I do not think this issue is related.
