### ISSUE TITLE
Put config file in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by Anas-Sherif** [darkhz/bluetuith#25]

**Comment by Anas-Sherif** [comment]
did it in #26

**Comment by darkhz** [comment]
Why would you need to put an application's configuration in the user's home directory? The appropriate place is the .config directory itself.

And in the event the .config directory isn't present,  bluetuith will automatically put its configuration folder and files in your home directory.

**Comment by Anas-Sherif** [comment]
the request isn't to put it in the home folder, it's to put it in $XDG_CONFIG_HOME instead of .config (on my system $XDG_CONFIG_HOME isn't .config)

**Comment by darkhz** [comment]
Sorry, I misinterpreted the issue, I only skimmed through the description and assumed you meant the home directory. I'll look into merging this.

**Comment by darkhz** [comment]
This issue has been fixed in the latest release
