### ISSUE TITLE
add option to hide/disable obex agent error on startup

### ISSUE THREAD

**Issue by craftyguy** [darkhz/bluetuith#29]
I don't use OBEX, and don't plan to, but use bluetuith *constantly* for managing bluetooth headsets and other peripherials. The warning on start is quite annoying :)

**Comment by darkhz** [comment]
@craftyguy okay, maybe a 'disable-warning' option of some sort should do right? The warning exists in case users need to check for any OBEX/Network related issues. This can be implemented.

**Comment by darkhz** [comment]
This feature has now been implemented with the `no-warning` command-line option.

To disable warnings, it can be done via the command-line:
```
bluetuith --no-warning
```

Or by setting the configuration parameter:
```
no-warning: true
```
