### ISSUE TITLE
Change navigation keys?

### ISSUE THREAD

**Issue by hacktail** [darkhz/bluetuith#31]
Hi, is there some way to change the navigation keybindings? I've got a Nordic keyboard setup which means that the standard `h j k l` has to be replaced into `j k l ö`, as it will otherwise defeat the purpose of not using other forms of navigation.

**Comment by darkhz** [comment]
There is currently no way to change the navigation keybindings, but it can be implemented.

**Comment by hacktail** [comment]
> There is currently no way to change the navigation keybindings, but it can be implemented.

W

**Comment by hacktail** [comment]
- [ ] 

> There is currently no way to change the navigation keybindings, but it can be implemented.

I would be extremely grateful if you did, can be a deal breaker sometimes.

**Comment by darkhz** [comment]
Okay, this will be implemented in the next release

**Comment by darkhz** [comment]
This has now been implemented in this release.

To change the navigation keys, it can be done by setting configuration parameters:
```
keybindings {
    # Similar to pressing the 'Up' key
    NavigateUp: 'k'

    # Similar to pressing the 'Down' key
    NavigateDown: 'l'

    # Similar to pressing the 'Right' key
    NavigateRight: 'j'

    # Similar to pressing the 'Left' key
    NavigateLeft: 'ö'
}
```

**Comment by hacktail** [comment]
> This has now been implemented in this release.
> 
> To change the navigation keys, it can be done by setting configuration parameters:
> 
> ```
> keybindings {
>     # Similar to pressing the 'Up' key
>     NavigateUp: 'k'
> 
>     # Similar to pressing the 'Down' key
>     NavigateDown: 'l'
> 
>     # Similar to pressing the 'Right' key
>     NavigateRight: 'j'
> 
>     # Similar to pressing the 'Left' key
>     NavigateLeft: 'ö'
> }
> ```

Thank you so much! Maybe I should've made my own PR, maybe I'll do that next time :)
