### ISSUE TITLE
Pairing keyboard - increase display time of the access number

### ISSUE THREAD

**Issue by jhmj-io** [darkhz/bluetuith#32]
Whilst pairing a keyboard (MX keys) entering a code on the keyboard is customary. This code is displayed in the bluetuith interface - display time is very short though.

**Comment by darkhz** [comment]
Are you on the latest version? Can you perhaps send a screenshot of the code display that you are getting?

**Comment by jhmj-io** [comment]
yes, I'm on the latest version 

./bluetuith --version says: Bluetuith v[]

![image](https://github.com/darkhz/bluetuith/assets/79975610/bf68953c-54ea-4099-81b3-8e6b00ed4dc2)

**Comment by darkhz** [comment]
Okay, from the screenshot it does look like it is the latest version. I think you must have compiled the program yourself, which is why the correct version is not displaying properly.

I will look into this.

**Comment by jhmj-io** [comment]
yes I compiled myself - Fedora

**Comment by darkhz** [comment]
@jhmj-io  Just to confirm, the message displayed is "Passkey for MX keys is 123456, entered ------"?

**Comment by jhmj-io** [comment]
YESS confirmed!
![image](https://github.com/darkhz/bluetuith/assets/79975610/fcd39dcb-b986-47f6-91df-8e456c3e9da5)

**Comment by darkhz** [comment]
This feature has now been implemented in this release. All pairing codes and requests will now be shown indefinitely within a popup, and you can close the popup by either pressing `Escape` or clicking the 'X' button.
