### ISSUE TITLE
v1.8.0 have some problem

### ISSUE THREAD

**Issue by newyorkthink** [darkhz/bluetuith#34]
![image](https://github.com/darkhz/bluetuith/assets/87791643/a6a29778-cb3c-43d1-8294-0a42822837b6)

what is mean

**Comment by darkhz** [comment]
This is not an issue, you probably have another Bluetooth manager running, so you will not be able to send files with this application. To make the warning go away, close the other manager and restart the application.

**Comment by newyorkthink** [comment]
but i never have other bluetooth manager
