### ISSUE TITLE
v1.8.0 bug cannot use "enter" keyboard

### ISSUE THREAD

**Issue by newyorkthink** [darkhz/bluetuith#35]
![image](https://github.com/darkhz/bluetuith/assets/87791643/19b5d1ab-ae26-4c9f-9fc9-8f9163726934)

when i select the one item, and click keyboard "enter"

it cannnot change to Adapter or Device

**Comment by darkhz** [comment]
Can you perhaps record a GIF/video to better highlight the issue?

**Comment by newyorkthink** [comment]
> Can you perhaps record a GIF/video to better highlight the issue?

i never use record video, i just use flameshot

**Comment by darkhz** [comment]
Since you have not provided information about the issue clearly, this issue will be closed. You can reopen it after editing your issue description with more details, and supplement it with a recording.
