### ISSUE TITLE
Full Repology badge?

### ISSUE THREAD

**Issue by tombh** [darkhz/bluetuith#38]
I wasn't aware that the [![Packaging status](https://repology.org/badge/tiny-repos/bluetuith.svg)](https://repology.org/project/bluetuith/versions) badge referred to where I could install this from. Maybe this one could be used instead? But at the bottom of the README instead.

[![Packaging status](https://repology.org/badge/vertical-allrepos/bluetuith.svg)](https://repology.org/project/bluetuith/versions)

Some context. When I clicked on the documentation link in the bottom of the README, I assumed that the new "VIEW DOCUMENTATION" link I was seeing was actually just a link to the same page. So not only did I not click on it, I also assumed there were no installation instructions. So then I went to the Nix packages search website to see if somebody had made a package for it, which they very much had. I then wondered why that wasn't mentioned in the docs, "surely there must be more docs", I thought. After more clicking I finally decided to click on "VIEW DOCUMENTATION" out of curiosity and then saw the installation instructions at last. But still no mention of a Nix package! I had never heard of Repology, so again, didn't click on the link to it at first. Of course, once I landed on https://repology.org/project/bluetuith/versions everything made sense.

I think just putting the full Repology badge in the README would be the easiest fix for this.

**Comment by darkhz** [comment]
Noted. A repology badge will be added to the README in the next release.
