### ISSUE TITLE
Would you port this great tool to FreeBSD

### ISSUE THREAD

**Issue by dr3mro** [darkhz/bluetuith#41]
Hello, 
FreeBSD does not have any thing like this great tool, so would you port this tool to FreeBSD
I hope you find this a good point
Thanks

**Comment by darkhz** [comment]
You may need to find experienced maintainers who can port this package to FreeBSD, since I haven't worked with it before.

**Comment by dr3mro** [comment]
The issue is freeBSD has no Bluetooth connection manager and users have to
enter multiple commands to initiate a connection
Your work is very creative and freeBSD needs something like this
Linux has a lot of tools already

**Comment by darkhz** [comment]
I could perhaps build and publish binaries for FreeBSD, I will do so in the next release.

**Comment by darkhz** [comment]
This tool relies on BlueZ to manage bluetooth. I don't think the FreeBSD has the API necessary for this application to work.
