### ISSUE TITLE
cannot print version without dbus connection

### ISSUE THREAD

**Issue by katexochen** [darkhz/bluetuith#47]
In some situations, dbus isn't available but I still would like to check bluetuith's version. When checking the version of a tool, I'd expect the tool to not do much beside printing a simple embedded string. Right now, this fails with

```
$ bluetuith --version
[!] Could not initialize bluez DBus connection
```

**Comment by darkhz** [comment]
Interesting, I will look into this.

**Comment by darkhz** [comment]
This issue has been fixed.

**Comment by katexochen** [comment]
Thanks!
