### ISSUE TITLE
Order of help menu sections is not deterministic

### ISSUE THREAD

**Issue by jackkinsey** [darkhz/bluetuith#49]
Repeatedly opening and closing the help menu, I notice that every so often the sections are ordered differently from what appears to be the default/normal/correct order.

So, e.g., instead of:

![image](https://github.com/darkhz/bluetuith/assets/7231687/bdaa9852-ed16-497e-a69f-3fe01912748a)

I might get something like this:

![image](https://github.com/darkhz/bluetuith/assets/7231687/88a229c9-1b42-44fb-ac37-d99d1e44b38e)

This is obviously not a big deal at all, but I thought it was curious. Love the application!

**Comment by darkhz** [comment]
Yes, this is expected. To be more technical, all the help items are stored in a map, and as such the items are unordered and will produce different output every time the map is accessed. I didn't think it was important to maintain the order of the help items, and hence the random arrangement of the items.
