### ISSUE TITLE
[FEAT] Supporting Vim style navigation and keymap 

### ISSUE THREAD

**Issue by Krr0ptioN** [darkhz/bluetuith#51]
## Description

Vim style navigation is broadly considered something as general feature for most of TUI application. The existing conventional navigation do not conflict with Vim navigation. So why not?

**NOTE:** I am guessing the maintainer is not a fan of Vim, so that's why the description might seem like a sales pitch :)

**Comment by darkhz** [comment]
Take a look at #31 for implementing basic vim-like navigation.

**Comment by Krr0ptioN** [comment]
I didn't see that and actually I was about to PR some changes, although it seems like no issue is left to solve.
Repeatable navigational commands could be interesting, e.g. `3j` three times navigate to down. 

Good project though, thanks.

**Comment by darkhz** [comment]
I will consider implementing this feature.

**Comment by kohane27** [comment]
Thanks for adding support for vim-like navigation! I'm just happy with the following:

```
keybindings {
    NavigateUp: 'k'
    NavigateDown: 'j'
    NavigateRight: 'l'
    NavigateLeft: 'h'
}
```

Thank you and have a good day!
