### ISSUE TITLE
[Solved] Cannot set adapter power state

### ISSUE THREAD

**Issue by DavShaw** [darkhz/bluetuith#54]
Hello, I just installed Bluetuith, but when I try to power on the adapter I got that problem... (I cannot scan, pair or connect cuz adapter's powered off)

![image](https://github.com/darkhz/bluetuith/assets/119999924/34f24f5d-2049-4e36-b9bb-2f406952657f)

**Comment by darkhz** [comment]
Hmm, does setting the power for that adapter work while using bluetoothctl or other Bluetooth managers?

**Comment by darkhz** [comment]
@DavShaw check whether your bluetooth kernel modules are loaded correctly, and check whether the bluetooth service is running properly with `systemctl status bluetooth.service`, if you use **systemd** for example. Post the journal for the service or relevant `dmesg` logs here.
