### ISSUE TITLE
Authentication aborting

### ISSUE THREAD

**Issue by jon4hz** [darkhz/bluetuith#6]
Hi, this project looks super interesting!

I tried to use bluetuith to connect to a flipperzero, which requires a code for pairing, but unfortunately it didn't work. The authentication code was displayed for about a second on the flipper and then the bluetuith returned `Error: Authentication cancelled`. Is pairing with authentication supposed to work?

**Comment by darkhz** [comment]
Pairing with authentication works, I use it to pair and connect to my phone and headset.

Can you try pairing and connecting with bluetoothctl? Also if possible, a small video demonstrating the issue would be helpful.

**Comment by darkhz** [comment]
This issue will be closed due to inactivity. You can reopen it  the by posting the information I mentioned above.
