### ISSUE TITLE
hjkl to move around by default

### ISSUE THREAD

**Issue by sweenu** [darkhz/bluetuith#61]
Could we add vim-like movement by doing, by default :
h -> left
j -> down
k -> up
l -> right

It has the advantage of not forcing you to move your right hand to the arrow keys, that is why vim does it like that. It's more efficient.
Most tui applications I know have this by default so I think is good UX to have it by default here too.

**Comment by darkhz** [comment]
Please have a look at #51.

**Comment by sweenu** [comment]
So I saw that I could add those manually, and that's good! My proposal was to make it default for new users to use bluetuith like they expect to use (almost) any tui.

Thanks for bluetuith, it's really good!
