### ISSUE TITLE
FEATURE REQUEST: Disconnect from a device binding

### ISSUE THREAD

**Issue by gordoncyu** [darkhz/bluetuith#63]
There does not seem to be a way to disconnect from an individual device. It may not be common in your workflow but it feels like a pretty big hole when you don't have it.

**Comment by gordoncyu** [comment]
Nevermind, apparently c toggles connected state. Please change the help to indicate this rather than just saying "Pair with selected device"

**Comment by darkhz** [comment]
Ah, I apologize, the documentation should have been more clear. Most device options are toggleable, and I will have to edit the documentation and the menu descriptions as well to properly define what operations can be toggled. Thank you for the PR, I'll merge it soon.
