### ISSUE TITLE
Quit on Ctrl-C

### ISSUE THREAD

**Issue by xeruf** [darkhz/bluetuith#9]
I am so used to that, always have to search for Q ^^

**Comment by darkhz** [comment]
I'll consider implementing this.

**Comment by darkhz** [comment]
Do look at #8, and see if the requested feature in that issue will suffice. I blocked Ctrl+C to prevent accidental quitting. Pressing Q+y wouldn't be that tedious, I suppose. If this issue gains traction(i.e if more people request this feature), I can implement it.

**Comment by xeruf** [comment]
Ctrl-C is easier to reach and a habit in the terminal. How would I hit that accidentally? I would really like to have it as an option, too.

**Comment by darkhz** [comment]
Hmm, I will look into it. Perhaps if I made keybindings configurable, it would be better for everyone.

**Comment by xeruf** [comment]
that was also a thought of mine, but I think that might be unnecessary work
just follow standards - Ctrl-C aborts almost any terminal application, I do not see why this one should be different

**Comment by darkhz** [comment]
I will consider this
